# Generated by Django 5.2 on 2025-05-07 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_add_missing_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.service')),
                ('service_provider', models.ForeignKey(limit_choices_to={'user_type': 'service_provider'}, on_delete=django.db.models.deletion.CASCADE, to='users.serviceproviderprofile')),
            ],
        ),
    ]
