# Generated by Django 5.2 on 2025-05-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('service_provider', 'Service Provider')], default='client', max_length=20),
        ),
    ]
